on:
  push:
    branches:
      - main
      - login-gcr.io # Update this as needed

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-22.04
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Authenticate using the token stored in GitHub Secrets
      - name: Authenticate to GCP
        env:
          GCP_ACCESS_TOKEN: ${{ secrets.GCP_ACCESS_TOKEN }}
        run: |
          echo $GCP_ACCESS_TOKEN | gcloud auth activate-service-account --key-file=<(echo $GCP_ACCESS_TOKEN | base64 --decode)

      # Configure Docker to use gcloud
      - name: gcloud Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Setup docker buildx
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      # Build and push the Docker image
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/summer-monument-436716-f5/pitt-cs-1660-build-and-push-image-hehua-fan/my-image:latest

# Alternative example: Manually running docker build and push commands
      - name: Build and Push Without Buildx
        env:
          GCP_ACCESS_TOKEN: ${{ secrets.GCP_ACCESS_TOKEN }}
        run: |
          echo $GCP_ACCESS_TOKEN | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/summer-monument-436716-f5/pitt-cs-1660-build-and-push-image-hehua-fan/my-image:v1 .
          docker push us-central1-docker.pkg.dev/summer-monument-436716-f5/pitt-cs-1660-build-and-push-image-hehua-fan/my-image:v1